#!/usr/bin/env bash

#
# Find script path
#
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
    DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

#
# Includes
#
source $DIR/../../functions/cmd-available

#
# AWS functions
#
function install {
    pip install awscli
}

function update {
    pip install awscli --upgrade --quiet
}

# Check for AWS
if ! cmd-available aws
then
    install
else
    update
fi

exit 0
